// Generated by gencpp from file serial_itri_driver/command_keyResponse.msg
// DO NOT EDIT!


#ifndef SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYRESPONSE_H
#define SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_itri_driver
{
template <class ContainerAllocator>
struct command_keyResponse_
{
  typedef command_keyResponse_<ContainerAllocator> Type;

  command_keyResponse_()
    : ans(false)  {
    }
  command_keyResponse_(const ContainerAllocator& _alloc)
    : ans(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ans_type;
  _ans_type ans;





  typedef boost::shared_ptr< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct command_keyResponse_

typedef ::serial_itri_driver::command_keyResponse_<std::allocator<void> > command_keyResponse;

typedef boost::shared_ptr< ::serial_itri_driver::command_keyResponse > command_keyResponsePtr;
typedef boost::shared_ptr< ::serial_itri_driver::command_keyResponse const> command_keyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_itri_driver::command_keyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_itri_driver::command_keyResponse_<ContainerAllocator1> & lhs, const ::serial_itri_driver::command_keyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ans == rhs.ans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_itri_driver::command_keyResponse_<ContainerAllocator1> & lhs, const ::serial_itri_driver::command_keyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_itri_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c4b05f69b62d4641eb7409883f6359d";
  }

  static const char* value(const ::serial_itri_driver::command_keyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c4b05f69b62d464ULL;
  static const uint64_t static_value2 = 0x1eb7409883f6359dULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_itri_driver/command_keyResponse";
  }

  static const char* value(const ::serial_itri_driver::command_keyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ans\n"
;
  }

  static const char* value(const ::serial_itri_driver::command_keyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct command_keyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_itri_driver::command_keyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_itri_driver::command_keyResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ans);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYRESPONSE_H
