// Generated by gencpp from file serial_itri_driver/command_keyRequest.msg
// DO NOT EDIT!


#ifndef SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYREQUEST_H
#define SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_itri_driver
{
template <class ContainerAllocator>
struct command_keyRequest_
{
  typedef command_keyRequest_<ContainerAllocator> Type;

  command_keyRequest_()
    : init(false)  {
    }
  command_keyRequest_(const ContainerAllocator& _alloc)
    : init(false)  {
  (void)_alloc;
    }



   typedef uint8_t _init_type;
  _init_type init;





  typedef boost::shared_ptr< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct command_keyRequest_

typedef ::serial_itri_driver::command_keyRequest_<std::allocator<void> > command_keyRequest;

typedef boost::shared_ptr< ::serial_itri_driver::command_keyRequest > command_keyRequestPtr;
typedef boost::shared_ptr< ::serial_itri_driver::command_keyRequest const> command_keyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_itri_driver::command_keyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_itri_driver::command_keyRequest_<ContainerAllocator1> & lhs, const ::serial_itri_driver::command_keyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.init == rhs.init;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_itri_driver::command_keyRequest_<ContainerAllocator1> & lhs, const ::serial_itri_driver::command_keyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_itri_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d4dfd2ecc8e1df89b8c57312822d6f7";
  }

  static const char* value(const ::serial_itri_driver::command_keyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d4dfd2ecc8e1df8ULL;
  static const uint64_t static_value2 = 0x9b8c57312822d6f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_itri_driver/command_keyRequest";
  }

  static const char* value(const ::serial_itri_driver::command_keyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool init\n"
;
  }

  static const char* value(const ::serial_itri_driver::command_keyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct command_keyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_itri_driver::command_keyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_itri_driver::command_keyRequest_<ContainerAllocator>& v)
  {
    s << indent << "init: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.init);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_ITRI_DRIVER_MESSAGE_COMMAND_KEYREQUEST_H
