// Generated by gencpp from file navigation_controller/command.msg
// DO NOT EDIT!


#ifndef NAVIGATION_CONTROLLER_MESSAGE_COMMAND_H
#define NAVIGATION_CONTROLLER_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <navigation_controller/commandRequest.h>
#include <navigation_controller/commandResponse.h>


namespace navigation_controller
{

struct command
{

typedef commandRequest Request;
typedef commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command
} // namespace navigation_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_controller::command > {
  static const char* value()
  {
    return "f75d6c7ceee1c8023f1b356191a18d49";
  }

  static const char* value(const ::navigation_controller::command&) { return value(); }
};

template<>
struct DataType< ::navigation_controller::command > {
  static const char* value()
  {
    return "navigation_controller/command";
  }

  static const char* value(const ::navigation_controller::command&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_controller::commandRequest> should match
// service_traits::MD5Sum< ::navigation_controller::command >
template<>
struct MD5Sum< ::navigation_controller::commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_controller::command >::value();
  }
  static const char* value(const ::navigation_controller::commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_controller::commandRequest> should match
// service_traits::DataType< ::navigation_controller::command >
template<>
struct DataType< ::navigation_controller::commandRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_controller::command >::value();
  }
  static const char* value(const ::navigation_controller::commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_controller::commandResponse> should match
// service_traits::MD5Sum< ::navigation_controller::command >
template<>
struct MD5Sum< ::navigation_controller::commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_controller::command >::value();
  }
  static const char* value(const ::navigation_controller::commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_controller::commandResponse> should match
// service_traits::DataType< ::navigation_controller::command >
template<>
struct DataType< ::navigation_controller::commandResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_controller::command >::value();
  }
  static const char* value(const ::navigation_controller::commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_CONTROLLER_MESSAGE_COMMAND_H
