// Generated by gencpp from file navigation_controller/command_status.msg
// DO NOT EDIT!


#ifndef NAVIGATION_CONTROLLER_MESSAGE_COMMAND_STATUS_H
#define NAVIGATION_CONTROLLER_MESSAGE_COMMAND_STATUS_H

#include <ros/service_traits.h>


#include <navigation_controller/command_statusRequest.h>
#include <navigation_controller/command_statusResponse.h>


namespace navigation_controller
{

struct command_status
{

typedef command_statusRequest Request;
typedef command_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command_status
} // namespace navigation_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_controller::command_status > {
  static const char* value()
  {
    return "33ed9e193eaee162a578945b5dc27255";
  }

  static const char* value(const ::navigation_controller::command_status&) { return value(); }
};

template<>
struct DataType< ::navigation_controller::command_status > {
  static const char* value()
  {
    return "navigation_controller/command_status";
  }

  static const char* value(const ::navigation_controller::command_status&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_controller::command_statusRequest> should match
// service_traits::MD5Sum< ::navigation_controller::command_status >
template<>
struct MD5Sum< ::navigation_controller::command_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_controller::command_status >::value();
  }
  static const char* value(const ::navigation_controller::command_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_controller::command_statusRequest> should match
// service_traits::DataType< ::navigation_controller::command_status >
template<>
struct DataType< ::navigation_controller::command_statusRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_controller::command_status >::value();
  }
  static const char* value(const ::navigation_controller::command_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_controller::command_statusResponse> should match
// service_traits::MD5Sum< ::navigation_controller::command_status >
template<>
struct MD5Sum< ::navigation_controller::command_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_controller::command_status >::value();
  }
  static const char* value(const ::navigation_controller::command_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_controller::command_statusResponse> should match
// service_traits::DataType< ::navigation_controller::command_status >
template<>
struct DataType< ::navigation_controller::command_statusResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_controller::command_status >::value();
  }
  static const char* value(const ::navigation_controller::command_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_CONTROLLER_MESSAGE_COMMAND_STATUS_H
